// js/openings.js
// Küçük bir ECO/açılış veritabanı. En uzun eşleşen açılış döndürülür.

export const OPENINGS = [
  // --- Beyaz 1.e4 -----------------------------------------------------------
  { eco: 'C20', name: 'Açık Oyun', moves: 'e4 e5' },
  { eco: 'C21', name: 'Danimarka Gambiti', moves: 'e4 e5 d4 exd4' },
  { eco: 'C22', name: 'Merkez Oyunu', moves: 'e4 e5 Qh5' },
  { eco: 'C23', name: 'İskender Savunması', moves: 'e4 e5 Bc4 Nc6' },
  { eco: 'C25', name: 'Viyana Oyunu', moves: 'e4 e5 Nc3' },
  { eco: 'C26', name: 'Viyana Oyunu: Falkbeer', moves: 'e4 e5 Nc3 Nf6' },
  { eco: 'C28', name: 'Viyana Oyunu', moves: 'e4 e5 Nc3 Nf6 Bc4 Nxe4' },
  { eco: 'C30', name: 'King\'s Gambit', moves: 'e4 e5 f4' },
  { eco: 'C33', name: 'King\'s Gambit: Accepted', moves: 'e4 e5 f4 exf4' },
  { eco: 'C37', name: 'King\'s Gambit: Muzio', moves: 'e4 e5 f4 exf4 Nf3 g5' },
  { eco: 'C40', name: 'Latkovic Açılışı', moves: 'e4 e5 Nf3 f5' },
  { eco: 'C41', name: 'Fil Savunması', moves: 'e4 e5 Nf3 d6' },
  { eco: 'C42', name: 'Rus Cephesi', moves: 'e4 e5 Nf3 Nf6' },
  { eco: 'C44', name: 'İtalyan Oyunu', moves: 'e4 e5 Nf3 Nc6 Bc4' },
  { eco: 'C45', name: 'İskoç Oyunu', moves: 'e4 e5 Nf3 Nc6 d4 exd4' },
  { eco: 'C46', name: 'Üç At Oyunu', moves: 'e4 e5 Nf3 Nc6 Nc3' },
  { eco: 'C47', name: 'Dört At Oyunu', moves: 'e4 e5 Nf3 Nc6 Nc3 Nf6' },
  { eco: 'C48', name: 'Dört At: İspanyol Varyantı', moves: 'e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5' },
  { eco: 'C50', name: 'İtalyan Oyunu: Giuoco Piano', moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5' },
  { eco: 'C51', name: 'İtalyan: Evans Gambiti', moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5 b4' },
  { eco: 'C53', name: 'İtalyan: İki At Savunması', moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6' },
  { eco: 'C55', name: 'İki At: Fritz Varyantı', moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6 d4 exd4' },
  { eco: 'C57', name: 'İki At: Wilkes-Barre', moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5' },
  { eco: 'C60', name: 'İspanyol Oyunu (Ruy Lopez)', moves: 'e4 e5 Nf3 Nc6 Bb5' },
  { eco: 'C63', name: 'Ruy Lopez: Schliemann', moves: 'e4 e5 Nf3 Nc6 Bb5 f5' },
  { eco: 'C65', name: 'Ruy Lopez: Berlin Savunması', moves: 'e4 e5 Nf3 Nc6 Bb5 Nf6' },
  { eco: 'C67', name: 'Ruy Lopez: Berlin Açık', moves: 'e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4' },
  { eco: 'C68', name: 'Ruy Lopez: Değişim Varyantı', moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O' },
  { eco: 'C70', name: 'Ruy Lopez: Morphy Savunması', moves: 'e4 e5 Nf3 Nc6 Bb5 a6' },
  { eco: 'C78', name: 'Ruy Lopez: 5.O-O', moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O' },
  { eco: 'C84', name: 'Ruy Lopez: Kapalı', moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7' },
  { eco: 'C89', name: 'Ruy Lopez: Marshall Saldırısı', moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5' },
  { eco: 'C92', name: 'Ruy Lopez: Zaitsev', moves: 'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6' },
  { eco: 'B00', name: 'Owen Savunması', moves: 'e4 b6' },
  { eco: 'B01', name: 'İskandinav Savunması', moves: 'e4 d5' },
  { eco: 'B02', name: 'Alehin Savunması', moves: 'e4 Nf6' },
  { eco: 'B06', name: 'Modern (Robatsch) Savunma', moves: 'e4 g6' },
  { eco: 'B07', name: 'Pirc Savunması', moves: 'e4 d6' },
  { eco: 'B08', name: 'Pirc: Klasik Sistem', moves: 'e4 d6 d4 Nf6 Nc3 g6 Nf3 Bg7' },
  { eco: 'B10', name: 'Caro-Kann', moves: 'e4 c6' },
  { eco: 'B12', name: 'Caro-Kann: Klasik Varyant', moves: 'e4 c6 d4 d5' },
  { eco: 'B13', name: 'Caro-Kann: Değişim Varyantı', moves: 'e4 c6 d4 d5 exd5 cxd5' },
  { eco: 'B14', name: 'Caro-Kann: Panov-Botvinnik', moves: 'e4 c6 d4 d5 exd5 cxd5 c4' },
  { eco: 'B15', name: 'Caro-Kann: Klasik 4.Nc3', moves: 'e4 c6 d4 d5 Nc3' },
  { eco: 'B17', name: 'Caro-Kann: Steinitz', moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7' },
  { eco: 'B18', name: 'Caro-Kann: Klasik', moves: 'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5' },
  { eco: 'B20', name: 'Sicilya Savunması', moves: 'e4 c5' },
  { eco: 'B21', name: 'Sicilya: Smith-Morra', moves: 'e4 c5 d4 cxd4' },
  { eco: 'B22', name: 'Sicilya: Alapin', moves: 'e4 c5 c3' },
  { eco: 'B23', name: 'Sicilya: Kapalı', moves: 'e4 c5 Nc3' },
  { eco: 'B27', name: 'Sicilya: Hyperaccelerated Fianchetto', moves: 'e4 c5 Nf3 g6' },
  { eco: 'B30', name: 'Sicilya: Eski Sicilya', moves: 'e4 c5 Nf3 Nc6' },
  { eco: 'B32', name: 'Sicilya: Löwenthal', moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4' },
  { eco: 'B33', name: 'Sicilya: Sveshnikov', moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5' },
  { eco: 'B35', name: 'Sicilya: Hızlı Fianchetto', moves: 'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6' },
  { eco: 'B40', name: 'Sicilya: Fransız Bağlantı', moves: 'e4 c5 Nf3 e6' },
  { eco: 'B41', name: 'Sicilya: Kan', moves: 'e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6' },
  { eco: 'B44', name: 'Sicilya: Taimanov', moves: 'e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6' },
  { eco: 'B50', name: 'Sicilya: Klasik', moves: 'e4 c5 Nf3 d6' },
  { eco: 'B54', name: 'Sicilya: Açık', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4' },
  { eco: 'B56', name: 'Sicilya: Richter-Rauzer', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6' },
  { eco: 'B70', name: 'Sicilya: Ejderha', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6' },
  { eco: 'B80', name: 'Sicilya: Scheveningen', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6' },
  { eco: 'B90', name: 'Sicilya: Najdorf', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6' },
  { eco: 'B96', name: 'Sicilya: Najdorf 6.Bg5', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5' },
  { eco: 'B97', name: 'Sicilya: Najdorf: Poisoned Pawn', moves: 'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6' },
  { eco: 'C00', name: 'Fransız Savunması', moves: 'e4 e6' },
  { eco: 'C01', name: 'Fransız: Değişim Varyantı', moves: 'e4 e6 d4 d5 exd5 exd5' },
  { eco: 'C02', name: 'Fransız: İlerleme Varyantı', moves: 'e4 e6 d4 d5 e5' },
  { eco: 'C03', name: 'Fransız: Tarrasch', moves: 'e4 e6 d4 d5 Nd2' },
  { eco: 'C10', name: 'Fransız: Paulsen', moves: 'e4 e6 d4 d5 Nc3' },
  { eco: 'C11', name: 'Fransız: Klasik', moves: 'e4 e6 d4 d5 Nc3 Nf6' },
  { eco: 'C15', name: 'Fransız: Winawer', moves: 'e4 e6 d4 d5 Nc3 Bb4' },
  { eco: 'C19', name: 'Fransız: Winawer: İlerleme', moves: 'e4 e6 d4 d5 Nc3 Bb4 e5' },

  // --- Beyaz 1.d4 -----------------------------------------------------------
  { eco: 'A40', name: 'Modern Savunma', moves: 'd4 g6' },
  { eco: 'A41', name: 'Modern: Wade', moves: 'd4 g6 Nf3 Bg7 e3 d6' },
  { eco: 'A43', name: 'Eski Benoni', moves: 'd4 c5' },
  { eco: 'A45', name: 'Hint Savunması', moves: 'd4 Nf6' },
  { eco: 'A46', name: 'Hint: Neo-İndy', moves: 'd4 Nf6 Nf3' },
  { eco: 'A48', name: 'Hint: London Sistemi', moves: 'd4 Nf6 Nf3 g6' },
  { eco: 'A50', name: 'Hint: 2.c4', moves: 'd4 Nf6 c4' },
  { eco: 'A51', name: 'Budapest Gambiti', moves: 'd4 Nf6 c4 e5' },
  { eco: 'A53', name: 'Eski Hint Savunması', moves: 'd4 Nf6 c4 d6' },
  { eco: 'A56', name: 'Benoni', moves: 'd4 Nf6 c4 c5' },
  { eco: 'A57', name: 'Benko Gambiti', moves: 'd4 Nf6 c4 c5 d5 b5' },
  { eco: 'A60', name: 'Benoni Savunması', moves: 'd4 Nf6 c4 c5 d5 e6' },
  { eco: 'A70', name: 'Benoni: Klasik', moves: 'd4 Nf6 c4 c5 d5 e6 Nc3 exd5' },
  { eco: 'A80', name: 'Hollandaca Savunma', moves: 'd4 f5' },
  { eco: 'A82', name: 'Hollandaca: Staunton Gambiti', moves: 'd4 f5 e4' },
  { eco: 'A85', name: 'Hollandaca: Klasik', moves: 'd4 f5 c4 Nf6' },
  { eco: 'A87', name: 'Hollanda: Leningrad', moves: 'd4 f5 c4 Nf6 g3' },
  { eco: 'A90', name: 'Hollandaca: Taş Yapısı', moves: 'd4 f5 c4 Nf6 Nc3 e6' },
  { eco: 'D00', name: 'Blackmar-Diemer Gambiti', moves: 'd4 d5 e4' },
  { eco: 'D02', name: 'London Sistemi', moves: 'd4 Nf6 Nf3 d5 Bf4' },
  { eco: 'D06', name: 'Vezir Gambiti', moves: 'd4 d5 c4' },
  { eco: 'D08', name: 'Vezir Gambiti: Albin', moves: 'd4 d5 c4 e5' },
  { eco: 'D10', name: 'Slav Savunması', moves: 'd4 d5 c4 c6' },
  { eco: 'D11', name: 'Slav: 3.Nf3', moves: 'd4 d5 c4 c6 Nf3' },
  { eco: 'D17', name: 'Slav: Klasik', moves: 'd4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4' },
  { eco: 'D20', name: 'Vezir Gambiti: Kabul', moves: 'd4 d5 c4 dxc4' },
  { eco: 'D30', name: 'Vezir Gambiti: Slav Savunması', moves: 'd4 d5 c4 e6' },
  { eco: 'D35', name: 'Vezir Gambiti: Değişimsiz', moves: 'd4 d5 c4 e6 Nc3 Nf6' },
  { eco: 'D43', name: 'Vezir Gambiti: Slav Savunması', moves: 'd4 d5 c4 c6 Nf3 Nf6 Nc3' },
  { eco: 'D50', name: 'Vezir Gambiti: Dışborn', moves: 'd4 d5 c4 e6 Nc3 Nf6 Bg5' },
  { eco: 'D60', name: 'Ortodoks Savunma', moves: 'd4 d5 c4 e6 Nc3 Nf6 Bg5 Be7' },
  { eco: 'D70', name: 'Neo-Grünfeld', moves: 'd4 Nf6 c4 g6' },
  { eco: 'D80', name: 'Grünfeld Savunması', moves: 'd4 Nf6 c4 g6 Nc3 d5' },
  { eco: 'D85', name: 'Grünfeld: Değişim Varyantı', moves: 'd4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5' },
  { eco: 'D90', name: 'Grünfeld: Üç At', moves: 'd4 Nf6 c4 g6 Nc3 d5 Nf3' },
  { eco: 'D97', name: 'Grünfeld: Rus Sistemi', moves: 'd4 Nf6 c4 g6 Nc3 d5 Nf3 Bg7 Qb3' },
  { eco: 'E00', name: 'Katalan Açılışı', moves: 'd4 Nf6 c4 e6 g3 d5' },
  { eco: 'E01', name: 'Katalan: Kapalı', moves: 'd4 Nf6 c4 e6 g3 d5 Bg2' },
  { eco: 'E06', name: 'Katalan: Kapalı 6.Nf3', moves: 'd4 Nf6 c4 e6 g3 d5 Bg2 Be7 Nf3' },
  { eco: 'E10', name: 'Blumenfeld Gambiti', moves: 'd4 Nf6 c4 e6 Nf3 c5' },
  { eco: 'E12', name: 'Vezir Hint Savunması', moves: 'd4 Nf6 c4 e6 Nf3 b6' },
  { eco: 'E15', name: 'Vezir Hint: Bogo-İndy', moves: 'd4 Nf6 c4 e6 Nf3 b6 g3' },
  { eco: 'E20', name: 'Nimzo-Hint Savunması', moves: 'd4 Nf6 c4 e6 Nc3 Bb4' },
  { eco: 'E32', name: 'Nimzo: Klasik Varyant', moves: 'd4 Nf6 c4 e6 Nc3 Bb4 Qc2' },
  { eco: 'E40', name: 'Nimzo: Rubinstein', moves: 'd4 Nf6 c4 e6 Nc3 Bb4 e3' },
  { eco: 'E48', name: 'Nimzo: 4.e3 O-O', moves: 'd4 Nf6 c4 e6 Nc3 Bb4 e3 O-O' },
  { eco: 'E60', name: 'King\'s Hint Savunması', moves: 'd4 Nf6 c4 g6' },
  { eco: 'E70', name: 'King\'s Hint: Klasik', moves: 'd4 Nf6 c4 g6 Nc3 Bg7' },

  // --- Diğer ilk hamleler ---------------------------------------------------
  { eco: 'A00', name: 'İngiliz Açılışı', moves: 'c4' },
  { eco: 'A01', name: 'İngiliz: Kralaca Hint', moves: 'c4 Nf6' },
  { eco: 'A10', name: 'İngiliz: Anglo-Hint', moves: 'c4 Nf6 Nc3' },
  { eco: 'A20', name: 'İngiliz: Kralaca İngiliz', moves: 'c4 e5' },
  { eco: 'A22', name: 'İngiliz: Bremen Sistemi', moves: 'c4 e5 Nc3 Nf6' },
  { eco: 'A30', name: 'İngiliz: Simetrik', moves: 'c4 c5' },
  { eco: 'A02', name: 'Bird Açılışı', moves: 'f4' },
  { eco: 'A04', name: 'Réti Açılışı', moves: 'Nf3' },
  { eco: 'A05', name: 'Réti: King\'s Hint', moves: 'Nf3 Nf6' },
  { eco: 'A09', name: 'Réti Açılışı', moves: 'Nf3 d5' },
  { eco: 'A00b', name: 'Grob Açılışı', moves: 'g4' },
  { eco: 'A00c', name: 'Sokolsky Açılışı', moves: 'b4' },
  { eco: 'A00d', name: 'Sarıkapak Açılışı', moves: 'b3' },
  { eco: 'A00e', name: 'Larsen Açılışı', moves: 'b3 e5' },
  { eco: 'B00f', name: 'Nimzowitsch Savunması', moves: 'e4 Nc6' },
  { eco: 'B00g', name: 'Owen/Pirc tarzı: 1.e4 b6', moves: 'e4 b6' },
  { eco: 'D00b', name: 'Paleface Gambiti', moves: 'd4 d5 f4' },
  { eco: 'A80b', name: 'Staunton Taş Yapısı', moves: 'd4 f5 c4 Nf6 Nc3 e6 g3' },
];

// Hamle listesini SAN dizisi olarak al, en uzun eşleşen açılışı döndür.
export function detectOpening(sanMoves) {
  if (!sanMoves || sanMoves.length === 0) return null;
  const seq = sanMoves.join(' ');
  let best = null;
  for (const o of OPENINGS) {
    if (seq === o.moves || seq.startsWith(o.moves + ' ')) {
      if (!best || o.moves.length > best.moves.length) best = o;
    }
  }
  return best ? { eco: best.eco, name: best.name, line: best.moves } : null;
}
